
export const CustomersTypes = {

    UPDATE_CUSTOMERS_REQUEST: "UPDATE_CUSTOMERS_REQUEST",
    UPDATE_CUSTOMERS_SUCCESS: "UPDATE_CUSTOMERS_SUCCESS",
    UPDATE_CUSTOMERS_FAILED: "UPDATE_CUSTOMERS_FAILED",
    
};
  